---
- hosts: client
  remote_user: root
  vars:
  - nginx: nginx-1.14.0
  - conf: ./configure --prefix=/usr/local/nginx --with-pcre --with-http_stub_status_module --with-http_gzip_static_module --with-http_ssl_module --with-http_v2_module --user=omse --group=omse --error-log-path=/usr/local/nginx/logs/error.log --http-log-path=/usr/local/nginx/logs/access.log --pid-path=/var/run/nginx.pid --with-http_realip_module

  tasks:
  - name: 'Install Nginx lastest'
    get_url:
      url: http://nginx.org/download/{{nginx}}.tar.gz
      dest: /opt
  - name: 'Unarchive Nginx'
    unarchive:
      src: /opt/{{nginx}}.tar.gz
      dest: /opt/
      remote_src: true

  - name: 'Configuration Nginx'
    shell: cd /opt/{{nginx}};{{conf}};make&& make install
   
  - name: 'Copy Local Nginx_certs to client server'
    copy: src=/usr/local/nginx/conf/certs dest=/usr/local/nginx/conf/

  - name: 'Copy Local Nginx_config file to client server'
    copy: src=/usr/local/nginx/conf/config dest=/usr/local/nginx/conf/
